//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcAmerica.DesktopPOS.API.Client.InventoryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InventoryItem", Namespace="http://pcAmerica.com/DesktopPOS/InventoryService/DataContracts/2010/07/27")]
    [System.SerializableAttribute()]
    public partial class InventoryItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ChoiceItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsModifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemName2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private pcAmerica.DesktopPOS.API.Client.InventoryService.ItemType ItemTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.KitItem> KitItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastSoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.ModifierGroup> ModifierGroupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.ModifierItem> ModifierItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PromptDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PromptPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PromptQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StockLevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> ChoiceItems {
            get {
                return this.ChoiceItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ChoiceItemsField, value) != true)) {
                    this.ChoiceItemsField = value;
                    this.RaisePropertyChanged("ChoiceItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsModifier {
            get {
                return this.IsModifierField;
            }
            set {
                if ((this.IsModifierField.Equals(value) != true)) {
                    this.IsModifierField = value;
                    this.RaisePropertyChanged("IsModifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName2 {
            get {
                return this.ItemName2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ItemName2Field, value) != true)) {
                    this.ItemName2Field = value;
                    this.RaisePropertyChanged("ItemName2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNumberField, value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public pcAmerica.DesktopPOS.API.Client.InventoryService.ItemType ItemType {
            get {
                return this.ItemTypeField;
            }
            set {
                if ((this.ItemTypeField.Equals(value) != true)) {
                    this.ItemTypeField = value;
                    this.RaisePropertyChanged("ItemType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.KitItem> KitItems {
            get {
                return this.KitItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.KitItemsField, value) != true)) {
                    this.KitItemsField = value;
                    this.RaisePropertyChanged("KitItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastSold {
            get {
                return this.LastSoldField;
            }
            set {
                if ((this.LastSoldField.Equals(value) != true)) {
                    this.LastSoldField = value;
                    this.RaisePropertyChanged("LastSold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.ModifierGroup> ModifierGroups {
            get {
                return this.ModifierGroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifierGroupsField, value) != true)) {
                    this.ModifierGroupsField = value;
                    this.RaisePropertyChanged("ModifierGroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.ModifierItem> ModifierItems {
            get {
                return this.ModifierItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifierItemsField, value) != true)) {
                    this.ModifierItemsField = value;
                    this.RaisePropertyChanged("ModifierItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PromptDescription {
            get {
                return this.PromptDescriptionField;
            }
            set {
                if ((this.PromptDescriptionField.Equals(value) != true)) {
                    this.PromptDescriptionField = value;
                    this.RaisePropertyChanged("PromptDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PromptPrice {
            get {
                return this.PromptPriceField;
            }
            set {
                if ((this.PromptPriceField.Equals(value) != true)) {
                    this.PromptPriceField = value;
                    this.RaisePropertyChanged("PromptPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PromptQuantity {
            get {
                return this.PromptQuantityField;
            }
            set {
                if ((this.PromptQuantityField.Equals(value) != true)) {
                    this.PromptQuantityField = value;
                    this.RaisePropertyChanged("PromptQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StockLevel {
            get {
                return this.StockLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.StockLevelField, value) != true)) {
                    this.StockLevelField = value;
                    this.RaisePropertyChanged("StockLevel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemType", Namespace="http://pcAmerica.com/DesktopPOS/General/DataContracts/2009/10/26")]
    public enum ItemType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Standard = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MixNMatchDiscountAmount = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kit = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Choice = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ModifierGroup = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MixNMatchBulkPrice = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MixNMatchDiscountPercent = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Coupon = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GiftCard = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GiftCardFree = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Voucher = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoucherFree = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Donation = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pizza = 13,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KitItem", Namespace="http://pcAmerica.com/DesktopPOS/InventoryService/DataContracts/2010/07/27")]
    [System.SerializableAttribute()]
    public partial class KitItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNumberField, value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModifierGroup", Namespace="http://pcAmerica.com/DesktopPOS/InventoryService/DataContracts/2010/07/27")]
    [System.SerializableAttribute()]
    public partial class ModifierGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ChargedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ForcedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.ModifierItem> ModifierItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberToSelectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromptField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Charged {
            get {
                return this.ChargedField;
            }
            set {
                if ((this.ChargedField.Equals(value) != true)) {
                    this.ChargedField = value;
                    this.RaisePropertyChanged("Charged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Forced {
            get {
                return this.ForcedField;
            }
            set {
                if ((this.ForcedField.Equals(value) != true)) {
                    this.ForcedField = value;
                    this.RaisePropertyChanged("Forced");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNumberField, value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.ModifierItem> ModifierItems {
            get {
                return this.ModifierItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifierItemsField, value) != true)) {
                    this.ModifierItemsField = value;
                    this.RaisePropertyChanged("ModifierItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberToSelect {
            get {
                return this.NumberToSelectField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberToSelectField, value) != true)) {
                    this.NumberToSelectField = value;
                    this.RaisePropertyChanged("NumberToSelect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prompt {
            get {
                return this.PromptField;
            }
            set {
                if ((object.ReferenceEquals(this.PromptField, value) != true)) {
                    this.PromptField = value;
                    this.RaisePropertyChanged("Prompt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModifierItem", Namespace="http://pcAmerica.com/DesktopPOS/InventoryService/DataContracts/2010/07/27")]
    [System.SerializableAttribute()]
    public partial class ModifierItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNumberField, value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Context", Namespace="http://pcAmerica.com/DesktopPOS/General/DataContracts/2009/10/26")]
    [System.SerializableAttribute()]
    public partial class Context : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CashierIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CashierID {
            get {
                return this.CashierIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CashierIDField, value) != true)) {
                    this.CashierIDField = value;
                    this.RaisePropertyChanged("CashierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StationID {
            get {
                return this.StationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StationIDField, value) != true)) {
                    this.StationIDField = value;
                    this.RaisePropertyChanged("StationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreID {
            get {
                return this.StoreIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreIDField, value) != true)) {
                    this.StoreIDField = value;
                    this.RaisePropertyChanged("StoreID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pcAmerica.com/DesktopPOS/InventoryService/ServiceContracts/2010/07/27", ConfigurationName="InventoryService.InventoryService")]
    public interface InventoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/InventoryService/ServiceContracts/2010/07/27/Inve" +
            "ntoryService/GetItemList", ReplyAction="http://pcAmerica.com/DesktopPOS/InventoryService/ServiceContracts/2010/07/27/Inve" +
            "ntoryService/GetItemListResponse")]
        System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.InventoryItem> GetItemList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/InventoryService/ServiceContracts/2010/07/27/Inve" +
            "ntoryService/GetItemListExtended", ReplyAction="http://pcAmerica.com/DesktopPOS/InventoryService/ServiceContracts/2010/07/27/Inve" +
            "ntoryService/GetItemListExtendedResponse")]
        System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.InventoryItem> GetItemListExtended(pcAmerica.DesktopPOS.API.Client.InventoryService.Context context);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/InventoryService/ServiceContracts/2010/07/27/Inve" +
            "ntoryService/GetItem", ReplyAction="http://pcAmerica.com/DesktopPOS/InventoryService/ServiceContracts/2010/07/27/Inve" +
            "ntoryService/GetItemResponse")]
        pcAmerica.DesktopPOS.API.Client.InventoryService.InventoryItem GetItem(pcAmerica.DesktopPOS.API.Client.InventoryService.Context context, string itemNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/InventoryService/ServiceContracts/2010/07/27/Inve" +
            "ntoryService/GetModifierGroupsForItem", ReplyAction="http://pcAmerica.com/DesktopPOS/InventoryService/ServiceContracts/2010/07/27/Inve" +
            "ntoryService/GetModifierGroupsForItemResponse")]
        System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.ModifierGroup> GetModifierGroupsForItem(pcAmerica.DesktopPOS.API.Client.InventoryService.Context context, string itemNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/InventoryService/ServiceContracts/2010/07/27/Inve" +
            "ntoryService/GetIndividualModifiers", ReplyAction="http://pcAmerica.com/DesktopPOS/InventoryService/ServiceContracts/2010/07/27/Inve" +
            "ntoryService/GetIndividualModifiersResponse")]
        System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.ModifierItem> GetIndividualModifiers(pcAmerica.DesktopPOS.API.Client.InventoryService.Context context, string itemNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/InventoryService/ServiceContracts/2010/07/27/Inve" +
            "ntoryService/GetModifierItemsForModifierGroup", ReplyAction="http://pcAmerica.com/DesktopPOS/InventoryService/ServiceContracts/2010/07/27/Inve" +
            "ntoryService/GetModifierItemsForModifierGroupResponse")]
        System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.ModifierItem> GetModifierItemsForModifierGroup(pcAmerica.DesktopPOS.API.Client.InventoryService.Context context, string itemNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InventoryServiceChannel : pcAmerica.DesktopPOS.API.Client.InventoryService.InventoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InventoryServiceClient : System.ServiceModel.ClientBase<pcAmerica.DesktopPOS.API.Client.InventoryService.InventoryService>, pcAmerica.DesktopPOS.API.Client.InventoryService.InventoryService {
        
        public InventoryServiceClient() {
        }
        
        public InventoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InventoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.InventoryItem> GetItemList() {
            return base.Channel.GetItemList();
        }
        
        public System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.InventoryItem> GetItemListExtended(pcAmerica.DesktopPOS.API.Client.InventoryService.Context context) {
            return base.Channel.GetItemListExtended(context);
        }
        
        public pcAmerica.DesktopPOS.API.Client.InventoryService.InventoryItem GetItem(pcAmerica.DesktopPOS.API.Client.InventoryService.Context context, string itemNumber) {
            return base.Channel.GetItem(context, itemNumber);
        }
        
        public System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.ModifierGroup> GetModifierGroupsForItem(pcAmerica.DesktopPOS.API.Client.InventoryService.Context context, string itemNumber) {
            return base.Channel.GetModifierGroupsForItem(context, itemNumber);
        }
        
        public System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.ModifierItem> GetIndividualModifiers(pcAmerica.DesktopPOS.API.Client.InventoryService.Context context, string itemNumber) {
            return base.Channel.GetIndividualModifiers(context, itemNumber);
        }
        
        public System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.InventoryService.ModifierItem> GetModifierItemsForModifierGroup(pcAmerica.DesktopPOS.API.Client.InventoryService.Context context, string itemNumber) {
            return base.Channel.GetModifierItemsForModifierGroup(context, itemNumber);
        }
    }
}
