//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcAmerica.DesktopPOS.API.Client.CompanyInformationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pcAmerica.com/DesktopPOS/CompanyInformationService/ServiceContracts/2010/0" +
        "7/27", ConfigurationName="CompanyInformationService.CompanyInformationService")]
    public interface CompanyInformationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/CompanyInformationService/ServiceContracts/2010/0" +
            "7/27/CompanyInformationService/GetStoreIDs", ReplyAction="http://pcAmerica.com/DesktopPOS/CompanyInformationService/ServiceContracts/2010/0" +
            "7/27/CompanyInformationService/GetStoreIDsResponse")]
        System.Collections.Generic.List<string> GetStoreIDs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/CompanyInformationService/ServiceContracts/2010/0" +
            "7/27/CompanyInformationService/GetStationIDs", ReplyAction="http://pcAmerica.com/DesktopPOS/CompanyInformationService/ServiceContracts/2010/0" +
            "7/27/CompanyInformationService/GetStationIDsResponse")]
        System.Collections.Generic.List<string> GetStationIDs(string StoreID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/CompanyInformationService/ServiceContracts/2010/0" +
            "7/27/CompanyInformationService/GetDBInfo", ReplyAction="http://pcAmerica.com/DesktopPOS/CompanyInformationService/ServiceContracts/2010/0" +
            "7/27/CompanyInformationService/GetDBInfoResponse")]
        void GetDBInfo(ref string DatabaseName, ref string InstanceName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CompanyInformationServiceChannel : pcAmerica.DesktopPOS.API.Client.CompanyInformationService.CompanyInformationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyInformationServiceClient : System.ServiceModel.ClientBase<pcAmerica.DesktopPOS.API.Client.CompanyInformationService.CompanyInformationService>, pcAmerica.DesktopPOS.API.Client.CompanyInformationService.CompanyInformationService {
        
        public CompanyInformationServiceClient() {
        }
        
        public CompanyInformationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyInformationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyInformationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyInformationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<string> GetStoreIDs() {
            return base.Channel.GetStoreIDs();
        }
        
        public System.Collections.Generic.List<string> GetStationIDs(string StoreID) {
            return base.Channel.GetStationIDs(StoreID);
        }
        
        public void GetDBInfo(ref string DatabaseName, ref string InstanceName) {
            base.Channel.GetDBInfo(ref DatabaseName, ref InstanceName);
        }
    }
}
