//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcAmerica.DesktopPOS.API.Client.CustomerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageAction", Namespace="http://pcAmerica.com/DesktopPOS/CustomerService/DataContracts/2009/10/26")]
    public enum MessageAction : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreateOrUpdate = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://pcAmerica.com/DesktopPOS/CustomerService/DataContracts/2009/10/26")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AccountClosedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AccountMaxBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AccountOpenDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillToNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BonusPlanMemberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BonusPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ChargeAtCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckingAcctNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Contact1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Contact2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditCardExpirationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditCardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditCardTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DisabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscountLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float DiscountPercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriversLicenseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LoyaltyPlanIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MaxChargeAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxChargeNumDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MembershipExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumber1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumber2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumber3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumber4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrintCustomerNotesOnReceiptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferralSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RequiresPONumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResaleNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.CustomerService.ShipToInfo> ShipToInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TaxExemptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaxRateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TermsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AccountClosedDate {
            get {
                return this.AccountClosedDateField;
            }
            set {
                if ((this.AccountClosedDateField.Equals(value) != true)) {
                    this.AccountClosedDateField = value;
                    this.RaisePropertyChanged("AccountClosedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AccountMaxBalance {
            get {
                return this.AccountMaxBalanceField;
            }
            set {
                if ((this.AccountMaxBalanceField.Equals(value) != true)) {
                    this.AccountMaxBalanceField = value;
                    this.RaisePropertyChanged("AccountMaxBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AccountOpenDate {
            get {
                return this.AccountOpenDateField;
            }
            set {
                if ((this.AccountOpenDateField.Equals(value) != true)) {
                    this.AccountOpenDateField = value;
                    this.RaisePropertyChanged("AccountOpenDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((this.AccountTypeField.Equals(value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillToName {
            get {
                return this.BillToNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BillToNameField, value) != true)) {
                    this.BillToNameField = value;
                    this.RaisePropertyChanged("BillToName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BonusPlanMember {
            get {
                return this.BonusPlanMemberField;
            }
            set {
                if ((this.BonusPlanMemberField.Equals(value) != true)) {
                    this.BonusPlanMemberField = value;
                    this.RaisePropertyChanged("BonusPlanMember");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BonusPoints {
            get {
                return this.BonusPointsField;
            }
            set {
                if ((this.BonusPointsField.Equals(value) != true)) {
                    this.BonusPointsField = value;
                    this.RaisePropertyChanged("BonusPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ChargeAtCost {
            get {
                return this.ChargeAtCostField;
            }
            set {
                if ((this.ChargeAtCostField.Equals(value) != true)) {
                    this.ChargeAtCostField = value;
                    this.RaisePropertyChanged("ChargeAtCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckingAcctNum {
            get {
                return this.CheckingAcctNumField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckingAcctNumField, value) != true)) {
                    this.CheckingAcctNumField = value;
                    this.RaisePropertyChanged("CheckingAcctNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contact1 {
            get {
                return this.Contact1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Contact1Field, value) != true)) {
                    this.Contact1Field = value;
                    this.RaisePropertyChanged("Contact1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contact2 {
            get {
                return this.Contact2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Contact2Field, value) != true)) {
                    this.Contact2Field = value;
                    this.RaisePropertyChanged("Contact2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditCardExpiration {
            get {
                return this.CreditCardExpirationField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditCardExpirationField, value) != true)) {
                    this.CreditCardExpirationField = value;
                    this.RaisePropertyChanged("CreditCardExpiration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditCardNumber {
            get {
                return this.CreditCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditCardNumberField, value) != true)) {
                    this.CreditCardNumberField = value;
                    this.RaisePropertyChanged("CreditCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditCardType {
            get {
                return this.CreditCardTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditCardTypeField, value) != true)) {
                    this.CreditCardTypeField = value;
                    this.RaisePropertyChanged("CreditCardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerNumber {
            get {
                return this.CustomerNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNumberField, value) != true)) {
                    this.CustomerNumberField = value;
                    this.RaisePropertyChanged("CustomerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Disabled {
            get {
                return this.DisabledField;
            }
            set {
                if ((this.DisabledField.Equals(value) != true)) {
                    this.DisabledField = value;
                    this.RaisePropertyChanged("Disabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscountLevel {
            get {
                return this.DiscountLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountLevelField, value) != true)) {
                    this.DiscountLevelField = value;
                    this.RaisePropertyChanged("DiscountLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float DiscountPercentage {
            get {
                return this.DiscountPercentageField;
            }
            set {
                if ((this.DiscountPercentageField.Equals(value) != true)) {
                    this.DiscountPercentageField = value;
                    this.RaisePropertyChanged("DiscountPercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriversLicenseNumber {
            get {
                return this.DriversLicenseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DriversLicenseNumberField, value) != true)) {
                    this.DriversLicenseNumberField = value;
                    this.RaisePropertyChanged("DriversLicenseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LoyaltyPlanID {
            get {
                return this.LoyaltyPlanIDField;
            }
            set {
                if ((this.LoyaltyPlanIDField.Equals(value) != true)) {
                    this.LoyaltyPlanIDField = value;
                    this.RaisePropertyChanged("LoyaltyPlanID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaxChargeAmount {
            get {
                return this.MaxChargeAmountField;
            }
            set {
                if ((this.MaxChargeAmountField.Equals(value) != true)) {
                    this.MaxChargeAmountField = value;
                    this.RaisePropertyChanged("MaxChargeAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxChargeNumDays {
            get {
                return this.MaxChargeNumDaysField;
            }
            set {
                if ((this.MaxChargeNumDaysField.Equals(value) != true)) {
                    this.MaxChargeNumDaysField = value;
                    this.RaisePropertyChanged("MaxChargeNumDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MembershipExpirationDate {
            get {
                return this.MembershipExpirationDateField;
            }
            set {
                if ((this.MembershipExpirationDateField.Equals(value) != true)) {
                    this.MembershipExpirationDateField = value;
                    this.RaisePropertyChanged("MembershipExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber1 {
            get {
                return this.PhoneNumber1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumber1Field, value) != true)) {
                    this.PhoneNumber1Field = value;
                    this.RaisePropertyChanged("PhoneNumber1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber2 {
            get {
                return this.PhoneNumber2Field;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumber2Field, value) != true)) {
                    this.PhoneNumber2Field = value;
                    this.RaisePropertyChanged("PhoneNumber2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber3 {
            get {
                return this.PhoneNumber3Field;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumber3Field, value) != true)) {
                    this.PhoneNumber3Field = value;
                    this.RaisePropertyChanged("PhoneNumber3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber4 {
            get {
                return this.PhoneNumber4Field;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumber4Field, value) != true)) {
                    this.PhoneNumber4Field = value;
                    this.RaisePropertyChanged("PhoneNumber4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PrintCustomerNotesOnReceipt {
            get {
                return this.PrintCustomerNotesOnReceiptField;
            }
            set {
                if ((this.PrintCustomerNotesOnReceiptField.Equals(value) != true)) {
                    this.PrintCustomerNotesOnReceiptField = value;
                    this.RaisePropertyChanged("PrintCustomerNotesOnReceipt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferralSource {
            get {
                return this.ReferralSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferralSourceField, value) != true)) {
                    this.ReferralSourceField = value;
                    this.RaisePropertyChanged("ReferralSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RequiresPONumber {
            get {
                return this.RequiresPONumberField;
            }
            set {
                if ((this.RequiresPONumberField.Equals(value) != true)) {
                    this.RequiresPONumberField = value;
                    this.RaisePropertyChanged("RequiresPONumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResaleNumber {
            get {
                return this.ResaleNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ResaleNumberField, value) != true)) {
                    this.ResaleNumberField = value;
                    this.RaisePropertyChanged("ResaleNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecretCode {
            get {
                return this.SecretCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SecretCodeField, value) != true)) {
                    this.SecretCodeField = value;
                    this.RaisePropertyChanged("SecretCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.CustomerService.ShipToInfo> ShipToInfo {
            get {
                return this.ShipToInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToInfoField, value) != true)) {
                    this.ShipToInfoField = value;
                    this.RaisePropertyChanged("ShipToInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TaxExempt {
            get {
                return this.TaxExemptField;
            }
            set {
                if ((this.TaxExemptField.Equals(value) != true)) {
                    this.TaxExemptField = value;
                    this.RaisePropertyChanged("TaxExempt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaxRateID {
            get {
                return this.TaxRateIDField;
            }
            set {
                if ((this.TaxRateIDField.Equals(value) != true)) {
                    this.TaxRateIDField = value;
                    this.RaisePropertyChanged("TaxRateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Terms {
            get {
                return this.TermsField;
            }
            set {
                if ((object.ReferenceEquals(this.TermsField, value) != true)) {
                    this.TermsField = value;
                    this.RaisePropertyChanged("Terms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipToInfo", Namespace="http://pcAmerica.com/DesktopPOS/CustomerService/DataContracts/2009/10/26")]
    [System.SerializableAttribute()]
    public partial class ShipToInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumber1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceCustomerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber1 {
            get {
                return this.PhoneNumber1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumber1Field, value) != true)) {
                    this.PhoneNumber1Field = value;
                    this.RaisePropertyChanged("PhoneNumber1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceCustomerNumber {
            get {
                return this.ReferenceCustomerNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceCustomerNumberField, value) != true)) {
                    this.ReferenceCustomerNumberField = value;
                    this.RaisePropertyChanged("ReferenceCustomerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pcAmerica.com/DesktopPOS/CustomerService/ServiceContracts/2009/10/26", ConfigurationName="CustomerService.CustomerService")]
    public interface CustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/CustomerService/ServiceContracts/2009/10/26/Custo" +
            "merService/UpdateRecord", ReplyAction="http://pcAmerica.com/DesktopPOS/CustomerService/ServiceContracts/2009/10/26/Custo" +
            "merService/UpdateRecordResponse")]
        bool UpdateRecord(pcAmerica.DesktopPOS.API.Client.CustomerService.MessageAction action, pcAmerica.DesktopPOS.API.Client.CustomerService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/CustomerService/ServiceContracts/2009/10/26/Custo" +
            "merService/FindRecord", ReplyAction="http://pcAmerica.com/DesktopPOS/CustomerService/ServiceContracts/2009/10/26/Custo" +
            "merService/FindRecordResponse")]
        pcAmerica.DesktopPOS.API.Client.CustomerService.Customer FindRecord(string customerNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerServiceChannel : pcAmerica.DesktopPOS.API.Client.CustomerService.CustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<pcAmerica.DesktopPOS.API.Client.CustomerService.CustomerService>, pcAmerica.DesktopPOS.API.Client.CustomerService.CustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UpdateRecord(pcAmerica.DesktopPOS.API.Client.CustomerService.MessageAction action, pcAmerica.DesktopPOS.API.Client.CustomerService.Customer customer) {
            return base.Channel.UpdateRecord(action, customer);
        }
        
        public pcAmerica.DesktopPOS.API.Client.CustomerService.Customer FindRecord(string customerNumber) {
            return base.Channel.FindRecord(customerNumber);
        }
    }
}
