//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pcAmerica.DesktopPOS.API.Client.SalesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesTotals", Namespace="http://pcAmerica.com/DesktopPOS/SalesService/DataContracts/2010/07/27")]
    [System.SerializableAttribute()]
    public partial class SalesTotals : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GrandTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NetSalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalTaxField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GrandTotal {
            get {
                return this.GrandTotalField;
            }
            set {
                if ((this.GrandTotalField.Equals(value) != true)) {
                    this.GrandTotalField = value;
                    this.RaisePropertyChanged("GrandTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NetSales {
            get {
                return this.NetSalesField;
            }
            set {
                if ((this.NetSalesField.Equals(value) != true)) {
                    this.NetSalesField = value;
                    this.RaisePropertyChanged("NetSales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalTax {
            get {
                return this.TotalTaxField;
            }
            set {
                if ((this.TotalTaxField.Equals(value) != true)) {
                    this.TotalTaxField = value;
                    this.RaisePropertyChanged("TotalTax");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemSale", Namespace="http://pcAmerica.com/DesktopPOS/SalesService/DataContracts/2010/07/27")]
    [System.SerializableAttribute()]
    public partial class ItemSale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CashierIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateSoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CashierID {
            get {
                return this.CashierIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CashierIDField, value) != true)) {
                    this.CashierIDField = value;
                    this.RaisePropertyChanged("CashierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateSold {
            get {
                return this.DateSoldField;
            }
            set {
                if ((this.DateSoldField.Equals(value) != true)) {
                    this.DateSoldField = value;
                    this.RaisePropertyChanged("DateSold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((this.InvoiceNumberField.Equals(value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNumberField, value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Context", Namespace="http://pcAmerica.com/DesktopPOS/General/DataContracts/2009/10/26")]
    [System.SerializableAttribute()]
    public partial class Context : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CashierIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CashierID {
            get {
                return this.CashierIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CashierIDField, value) != true)) {
                    this.CashierIDField = value;
                    this.RaisePropertyChanged("CashierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StationID {
            get {
                return this.StationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StationIDField, value) != true)) {
                    this.StationIDField = value;
                    this.RaisePropertyChanged("StationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreID {
            get {
                return this.StoreIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreIDField, value) != true)) {
                    this.StoreIDField = value;
                    this.RaisePropertyChanged("StoreID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnHoldInfo", Namespace="http://pcAmerica.com/DesktopPOS/SalesService/DataContracts/2010/07/27")]
    [System.SerializableAttribute()]
    public partial class OnHoldInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CashierIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GrandTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LockedByStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OnHoldIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CashierID {
            get {
                return this.CashierIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CashierIDField, value) != true)) {
                    this.CashierIDField = value;
                    this.RaisePropertyChanged("CashierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GrandTotal {
            get {
                return this.GrandTotalField;
            }
            set {
                if ((this.GrandTotalField.Equals(value) != true)) {
                    this.GrandTotalField = value;
                    this.RaisePropertyChanged("GrandTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((this.InvoiceNumberField.Equals(value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Locked {
            get {
                return this.LockedField;
            }
            set {
                if ((this.LockedField.Equals(value) != true)) {
                    this.LockedField = value;
                    this.RaisePropertyChanged("Locked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LockedByStation {
            get {
                return this.LockedByStationField;
            }
            set {
                if ((object.ReferenceEquals(this.LockedByStationField, value) != true)) {
                    this.LockedByStationField = value;
                    this.RaisePropertyChanged("LockedByStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OnHoldID {
            get {
                return this.OnHoldIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OnHoldIDField, value) != true)) {
                    this.OnHoldIDField = value;
                    this.RaisePropertyChanged("OnHoldID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://pcAmerica.com/DesktopPOS/SalesService/DataContracts/2010/07/27")]
    [System.SerializableAttribute()]
    public partial class Invoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CashierIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GrandTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.SalesService.LineItem> LineItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LockedByStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NeedsToBeSentToKitchenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OnHoldIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private pcAmerica.DesktopPOS.API.Client.SalesService.OrderTypes OrderTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartySizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private pcAmerica.DesktopPOS.API.Client.SalesService.InfoForSplits SplitInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TipAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalTaxField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CashierID {
            get {
                return this.CashierIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CashierIDField, value) != true)) {
                    this.CashierIDField = value;
                    this.RaisePropertyChanged("CashierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GrandTotal {
            get {
                return this.GrandTotalField;
            }
            set {
                if ((this.GrandTotalField.Equals(value) != true)) {
                    this.GrandTotalField = value;
                    this.RaisePropertyChanged("GrandTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((this.InvoiceNumberField.Equals(value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.SalesService.LineItem> LineItems {
            get {
                return this.LineItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.LineItemsField, value) != true)) {
                    this.LineItemsField = value;
                    this.RaisePropertyChanged("LineItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Locked {
            get {
                return this.LockedField;
            }
            set {
                if ((this.LockedField.Equals(value) != true)) {
                    this.LockedField = value;
                    this.RaisePropertyChanged("Locked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LockedByStation {
            get {
                return this.LockedByStationField;
            }
            set {
                if ((object.ReferenceEquals(this.LockedByStationField, value) != true)) {
                    this.LockedByStationField = value;
                    this.RaisePropertyChanged("LockedByStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NeedsToBeSentToKitchen {
            get {
                return this.NeedsToBeSentToKitchenField;
            }
            set {
                if ((this.NeedsToBeSentToKitchenField.Equals(value) != true)) {
                    this.NeedsToBeSentToKitchenField = value;
                    this.RaisePropertyChanged("NeedsToBeSentToKitchen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OnHoldID {
            get {
                return this.OnHoldIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OnHoldIDField, value) != true)) {
                    this.OnHoldIDField = value;
                    this.RaisePropertyChanged("OnHoldID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public pcAmerica.DesktopPOS.API.Client.SalesService.OrderTypes OrderType {
            get {
                return this.OrderTypeField;
            }
            set {
                if ((this.OrderTypeField.Equals(value) != true)) {
                    this.OrderTypeField = value;
                    this.RaisePropertyChanged("OrderType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PartySize {
            get {
                return this.PartySizeField;
            }
            set {
                if ((this.PartySizeField.Equals(value) != true)) {
                    this.PartySizeField = value;
                    this.RaisePropertyChanged("PartySize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public pcAmerica.DesktopPOS.API.Client.SalesService.InfoForSplits SplitInfo {
            get {
                return this.SplitInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SplitInfoField, value) != true)) {
                    this.SplitInfoField = value;
                    this.RaisePropertyChanged("SplitInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TipAmount {
            get {
                return this.TipAmountField;
            }
            set {
                if ((this.TipAmountField.Equals(value) != true)) {
                    this.TipAmountField = value;
                    this.RaisePropertyChanged("TipAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalTax {
            get {
                return this.TotalTaxField;
            }
            set {
                if ((this.TotalTaxField.Equals(value) != true)) {
                    this.TotalTaxField = value;
                    this.RaisePropertyChanged("TotalTax");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoForSplits", Namespace="http://pcAmerica.com/DesktopPOS/SalesService/DataContracts/2010/07/27")]
    [System.SerializableAttribute()]
    public partial class InfoForSplits : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<decimal> GrandTotalForSplitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<bool> IsSplitPaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfSplitChecksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<decimal> GrandTotalForSplit {
            get {
                return this.GrandTotalForSplitField;
            }
            set {
                if ((object.ReferenceEquals(this.GrandTotalForSplitField, value) != true)) {
                    this.GrandTotalForSplitField = value;
                    this.RaisePropertyChanged("GrandTotalForSplit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<bool> IsSplitPaid {
            get {
                return this.IsSplitPaidField;
            }
            set {
                if ((object.ReferenceEquals(this.IsSplitPaidField, value) != true)) {
                    this.IsSplitPaidField = value;
                    this.RaisePropertyChanged("IsSplitPaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfSplitChecks {
            get {
                return this.NumberOfSplitChecksField;
            }
            set {
                if ((this.NumberOfSplitChecksField.Equals(value) != true)) {
                    this.NumberOfSplitChecksField = value;
                    this.RaisePropertyChanged("NumberOfSplitChecks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineItem", Namespace="http://pcAmerica.com/DesktopPOS/SalesService/DataContracts/2010/07/27")]
    [System.SerializableAttribute()]
    public partial class LineItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SentToKitchenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private pcAmerica.DesktopPOS.API.Client.SalesService.EntityState StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guest {
            get {
                return this.GuestField;
            }
            set {
                if ((object.ReferenceEquals(this.GuestField, value) != true)) {
                    this.GuestField = value;
                    this.RaisePropertyChanged("Guest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNumberField, value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SentToKitchen {
            get {
                return this.SentToKitchenField;
            }
            set {
                if ((this.SentToKitchenField.Equals(value) != true)) {
                    this.SentToKitchenField = value;
                    this.RaisePropertyChanged("SentToKitchen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public pcAmerica.DesktopPOS.API.Client.SalesService.EntityState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderTypes", Namespace="http://pcAmerica.com/DesktopPOS/General/DataContracts/2009/10/26")]
    public enum OrderTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ToStay = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ToGo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivery = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AskBefore = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AskAfter = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NewAuction = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuctionPickup = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DriveThru = 11,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityState", Namespace="http://pcAmerica.com/DesktopPOS/General/DataContracts/2009/10/26")]
    public enum EntityState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Existing = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCardPaymentProcessingResponse", Namespace="http://pcAmerica.com/DesktopPOS/PaymentService/DataContracts/2009/10/26")]
    [System.SerializableAttribute()]
    public partial class CreditCardPaymentProcessingResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApprovalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExpirationMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExpirationYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrePaidCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostAuthReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private pcAmerica.DesktopPOS.API.Client.SalesService.ProcessingType ProcessTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TipAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TransactionNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApprovalCode {
            get {
                return this.ApprovalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprovalCodeField, value) != true)) {
                    this.ApprovalCodeField = value;
                    this.RaisePropertyChanged("ApprovalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExpirationMonth {
            get {
                return this.ExpirationMonthField;
            }
            set {
                if ((this.ExpirationMonthField.Equals(value) != true)) {
                    this.ExpirationMonthField = value;
                    this.RaisePropertyChanged("ExpirationMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExpirationYear {
            get {
                return this.ExpirationYearField;
            }
            set {
                if ((this.ExpirationYearField.Equals(value) != true)) {
                    this.ExpirationYearField = value;
                    this.RaisePropertyChanged("ExpirationYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrePaidCard {
            get {
                return this.IsPrePaidCardField;
            }
            set {
                if ((this.IsPrePaidCardField.Equals(value) != true)) {
                    this.IsPrePaidCardField = value;
                    this.RaisePropertyChanged("IsPrePaidCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostAuthReferenceNumber {
            get {
                return this.PostAuthReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PostAuthReferenceNumberField, value) != true)) {
                    this.PostAuthReferenceNumberField = value;
                    this.RaisePropertyChanged("PostAuthReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public pcAmerica.DesktopPOS.API.Client.SalesService.ProcessingType ProcessType {
            get {
                return this.ProcessTypeField;
            }
            set {
                if ((this.ProcessTypeField.Equals(value) != true)) {
                    this.ProcessTypeField = value;
                    this.RaisePropertyChanged("ProcessType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber {
            get {
                return this.ReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNumberField, value) != true)) {
                    this.ReferenceNumberField = value;
                    this.RaisePropertyChanged("ReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TipAmount {
            get {
                return this.TipAmountField;
            }
            set {
                if ((this.TipAmountField.Equals(value) != true)) {
                    this.TipAmountField = value;
                    this.RaisePropertyChanged("TipAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransactionNumber {
            get {
                return this.TransactionNumberField;
            }
            set {
                if ((this.TransactionNumberField.Equals(value) != true)) {
                    this.TransactionNumberField = value;
                    this.RaisePropertyChanged("TransactionNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessingType", Namespace="http://pcAmerica.com/DesktopPOS/General/DataContracts/2009/10/26")]
    public enum ProcessingType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sale = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreAuth = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PostAuth = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Force = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Credit = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoidSale = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoidCredit = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoidPreAuth = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppliedPaymentResponse", Namespace="http://pcAmerica.com/DesktopPOS/PaymentService/DataContracts/2009/10/26")]
    [System.SerializableAttribute()]
    public partial class AppliedPaymentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ChangeAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaymentIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TipAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ChangeAmount {
            get {
                return this.ChangeAmountField;
            }
            set {
                if ((this.ChangeAmountField.Equals(value) != true)) {
                    this.ChangeAmountField = value;
                    this.RaisePropertyChanged("ChangeAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentIndex {
            get {
                return this.PaymentIndexField;
            }
            set {
                if ((this.PaymentIndexField.Equals(value) != true)) {
                    this.PaymentIndexField = value;
                    this.RaisePropertyChanged("PaymentIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TipAmount {
            get {
                return this.TipAmountField;
            }
            set {
                if ((this.TipAmountField.Equals(value) != true)) {
                    this.TipAmountField = value;
                    this.RaisePropertyChanged("TipAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27", ConfigurationName="SalesService.SalesService")]
    public interface SalesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/GetTotals", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/GetTotalsResponse")]
        pcAmerica.DesktopPOS.API.Client.SalesService.SalesTotals GetTotals(System.DateTime StartDateTime, System.DateTime EndDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/GetItemsSold", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/GetItemsSoldResponse")]
        System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.SalesService.ItemSale> GetItemsSold(System.DateTime StartDateTime, System.DateTime EndDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/GetOnHoldInvoicesForCashier", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/GetOnHoldInvoicesForCashierResponse")]
        System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.SalesService.OnHoldInfo> GetOnHoldInvoicesForCashier(pcAmerica.DesktopPOS.API.Client.SalesService.Context context);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/GetAllOnHoldInvoices", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/GetAllOnHoldInvoicesResponse")]
        System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.SalesService.OnHoldInfo> GetAllOnHoldInvoices(pcAmerica.DesktopPOS.API.Client.SalesService.Context context);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/VoidInvoice", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/VoidInvoiceResponse")]
        bool VoidInvoice(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber, bool SendVoidToKitchen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/StartNewInvoice", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/StartNewInvoiceResponse")]
        pcAmerica.DesktopPOS.API.Client.SalesService.Invoice StartNewInvoice(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, string onHoldID, string SectionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/SetPartySizeForInvoice", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/SetPartySizeForInvoiceResponse")]
        bool SetPartySizeForInvoice(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long InvoiceNumber, int PartySize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/GetInvoice", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/GetInvoiceResponse")]
        pcAmerica.DesktopPOS.API.Client.SalesService.Invoice GetInvoice(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/GetInvoiceHeader", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/GetInvoiceHeaderResponse")]
        pcAmerica.DesktopPOS.API.Client.SalesService.Invoice GetInvoiceHeader(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/LockInvoice", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/LockInvoiceResponse")]
        bool LockInvoice(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/UnLockInvoice", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/UnLockInvoiceResponse")]
        bool UnLockInvoice(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/ModifyItems", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/ModifyItemsResponse")]
        pcAmerica.DesktopPOS.API.Client.SalesService.Invoice ModifyItems(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber, System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.SalesService.LineItem> items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/PrintReceipt", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/PrintReceiptResponse")]
        bool PrintReceipt(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber, int splitCheckNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/EmailReceipt", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/EmailReceiptResponse")]
        bool EmailReceipt(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber, int splitCheckNumber, string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/SendToKitchen", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/SendToKitchenResponse")]
        bool SendToKitchen(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/ApplyCardPayment", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/ApplyCardPaymentResponse")]
        pcAmerica.DesktopPOS.API.Client.SalesService.AppliedPaymentResponse ApplyCardPayment(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber, int subCheckNumber, pcAmerica.DesktopPOS.API.Client.SalesService.CreditCardPaymentProcessingResponse response, int paymentIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/ApplyCashPayment", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/ApplyCashPaymentResponse")]
        pcAmerica.DesktopPOS.API.Client.SalesService.AppliedPaymentResponse ApplyCashPayment(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber, int subCheckNumber, decimal Amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/SplitInvoice", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/SplitInvoiceResponse")]
        pcAmerica.DesktopPOS.API.Client.SalesService.Invoice SplitInvoice(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber, int numberOfWays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/SplitInvoiceByGuest", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/SplitInvoiceByGuestResponse")]
        pcAmerica.DesktopPOS.API.Client.SalesService.Invoice SplitInvoiceByGuest(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/CombineSplits", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/CombineSplitsResponse")]
        pcAmerica.DesktopPOS.API.Client.SalesService.Invoice CombineSplits(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/EndInvoice", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/EndInvoiceResponse")]
        bool EndInvoice(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/EndSubCheck", ReplyAction="http://pcAmerica.com/DesktopPOS/SalesService/ServiceContracts/2010/07/27/SalesSer" +
            "vice/EndSubCheckResponse")]
        bool EndSubCheck(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber, short subCheckNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SalesServiceChannel : pcAmerica.DesktopPOS.API.Client.SalesService.SalesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesServiceClient : System.ServiceModel.ClientBase<pcAmerica.DesktopPOS.API.Client.SalesService.SalesService>, pcAmerica.DesktopPOS.API.Client.SalesService.SalesService {
        
        public SalesServiceClient() {
        }
        
        public SalesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public pcAmerica.DesktopPOS.API.Client.SalesService.SalesTotals GetTotals(System.DateTime StartDateTime, System.DateTime EndDateTime) {
            return base.Channel.GetTotals(StartDateTime, EndDateTime);
        }
        
        public System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.SalesService.ItemSale> GetItemsSold(System.DateTime StartDateTime, System.DateTime EndDateTime) {
            return base.Channel.GetItemsSold(StartDateTime, EndDateTime);
        }
        
        public System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.SalesService.OnHoldInfo> GetOnHoldInvoicesForCashier(pcAmerica.DesktopPOS.API.Client.SalesService.Context context) {
            return base.Channel.GetOnHoldInvoicesForCashier(context);
        }
        
        public System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.SalesService.OnHoldInfo> GetAllOnHoldInvoices(pcAmerica.DesktopPOS.API.Client.SalesService.Context context) {
            return base.Channel.GetAllOnHoldInvoices(context);
        }
        
        public bool VoidInvoice(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber, bool SendVoidToKitchen) {
            return base.Channel.VoidInvoice(context, invoiceNumber, SendVoidToKitchen);
        }
        
        public pcAmerica.DesktopPOS.API.Client.SalesService.Invoice StartNewInvoice(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, string onHoldID, string SectionID) {
            return base.Channel.StartNewInvoice(context, onHoldID, SectionID);
        }
        
        public bool SetPartySizeForInvoice(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long InvoiceNumber, int PartySize) {
            return base.Channel.SetPartySizeForInvoice(context, InvoiceNumber, PartySize);
        }
        
        public pcAmerica.DesktopPOS.API.Client.SalesService.Invoice GetInvoice(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber) {
            return base.Channel.GetInvoice(context, invoiceNumber);
        }
        
        public pcAmerica.DesktopPOS.API.Client.SalesService.Invoice GetInvoiceHeader(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber) {
            return base.Channel.GetInvoiceHeader(context, invoiceNumber);
        }
        
        public bool LockInvoice(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber) {
            return base.Channel.LockInvoice(context, invoiceNumber);
        }
        
        public bool UnLockInvoice(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber) {
            return base.Channel.UnLockInvoice(context, invoiceNumber);
        }
        
        public pcAmerica.DesktopPOS.API.Client.SalesService.Invoice ModifyItems(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber, System.Collections.Generic.List<pcAmerica.DesktopPOS.API.Client.SalesService.LineItem> items) {
            return base.Channel.ModifyItems(context, invoiceNumber, items);
        }
        
        public bool PrintReceipt(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber, int splitCheckNumber) {
            return base.Channel.PrintReceipt(context, invoiceNumber, splitCheckNumber);
        }
        
        public bool EmailReceipt(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber, int splitCheckNumber, string emailAddress) {
            return base.Channel.EmailReceipt(context, invoiceNumber, splitCheckNumber, emailAddress);
        }
        
        public bool SendToKitchen(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber) {
            return base.Channel.SendToKitchen(context, invoiceNumber);
        }
        
        public pcAmerica.DesktopPOS.API.Client.SalesService.AppliedPaymentResponse ApplyCardPayment(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber, int subCheckNumber, pcAmerica.DesktopPOS.API.Client.SalesService.CreditCardPaymentProcessingResponse response, int paymentIndex) {
            return base.Channel.ApplyCardPayment(context, invoiceNumber, subCheckNumber, response, paymentIndex);
        }
        
        public pcAmerica.DesktopPOS.API.Client.SalesService.AppliedPaymentResponse ApplyCashPayment(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber, int subCheckNumber, decimal Amount) {
            return base.Channel.ApplyCashPayment(context, invoiceNumber, subCheckNumber, Amount);
        }
        
        public pcAmerica.DesktopPOS.API.Client.SalesService.Invoice SplitInvoice(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber, int numberOfWays) {
            return base.Channel.SplitInvoice(context, invoiceNumber, numberOfWays);
        }
        
        public pcAmerica.DesktopPOS.API.Client.SalesService.Invoice SplitInvoiceByGuest(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber) {
            return base.Channel.SplitInvoiceByGuest(context, invoiceNumber);
        }
        
        public pcAmerica.DesktopPOS.API.Client.SalesService.Invoice CombineSplits(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber) {
            return base.Channel.CombineSplits(context, invoiceNumber);
        }
        
        public bool EndInvoice(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber) {
            return base.Channel.EndInvoice(context, invoiceNumber);
        }
        
        public bool EndSubCheck(pcAmerica.DesktopPOS.API.Client.SalesService.Context context, long invoiceNumber, short subCheckNumber) {
            return base.Channel.EndSubCheck(context, invoiceNumber, subCheckNumber);
        }
    }
}
